"""
To use, save a copy of this file, named configuration.py, to your local copy of the script repo
and update the values to to match your local machine and Archive-It credentials.
"""

# Folder where reports generated by the scripts should be saved.
script_output = 'INSERT-PATH'

# Archive-It APIs and credentials.
partner_api = 'https://partner.archive-it.org/api'
wasapi = 'https://warcs.archive-it.org/wasapi/v1/webdata'
inst_page = 'https://partner.archive-it.org/INSERT-NUMBER'
username = 'INSERT-USERNAME'
password = 'INSERT-PASSWORD'
